Lab/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(schema="public")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank()
     * @Assert\Type("string")
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @Assert\NotBlank()
     * @Assert\Type("string")
     * @ORM\Column(type="string", length=255)
     */
    private $family_name;

    /**
     * @Assert\NotBlank()
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email."
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $password;

    /**
     *
     * @Assert\Length(
     *      min=5,
     *      max=50
     * )
     */
    private $plainPassword;

    /**
     * @Assert\NotBlank()
     * @Assert\Url(
     *    message = "The url '{{ value }}' is not a valid url",
     * )
     * @ORM\Column(type="text", nullable=true)
     */
    private $image_url;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $token_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $facebook_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $google_id;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(type="datetime", length=255)
     */
    private $date_create;

    /**
     * @ORM\Column(type="datetime", length=255, nullable=true)
     */
    private $date_delete;

    /**
     * @ORM\Column(type="boolean")
     */
    private $check_cgu;

    /**
     * @ORM\Column(type="boolean")
     */
    private $check_newsletter;

    /**
     * @ORM\ManyToMany(targetEntity="Group", inversedBy="users")
     */
    private $groups;

    /**
     * @ORM\OneToMany(targetEntity=Ticket::class, cascade={"persist", "remove"}, mappedBy="user")
     */
    private $ticket;

    /**
     * @ORM\OneToMany(targetEntity=User::class, cascade={"persist", "remove"}, mappedBy="user")
     */
    private $prize;

    public function __construct()
    {
        $this->date_create = new \DateTime("Europe/Paris");
        $this->groups = new ArrayCollection();
        $this->ticket = new ArrayCollection();
        $this->prize = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getFamilyName(): ?string
    {
        return $this->family_name;
    }

    public function setFamilyName(string $family_name): self
    {
        $this->family_name = $family_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(?string $image_url): self
    {
        $this->image_url = $image_url;

        return $this;
    }


    /**
     * Add group
     *
     * @param \App\Entity\Group $group
     *
     * @return User
     */
    public function addGroup(\App\Entity\Group $group)
    {
        $this->groups[] = $group;

        return $this;
    }

    /**
     * Remove group
     *
     * @param \App\Entity\Group $group
     */
    public function removeGroup(\App\Entity\Group $group)
    {
        $this->groups->removeElement($group);
    }

    /**
     * Get groups
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * Add ticket.
     *
     * @param \App\Entity\Ticket $ticket
     *
     * @return User
     */
    public function addTicket(\App\Entity\Ticket $ticket)
    {
        $this->ticket[] = $ticket;

        return $this;
    }

    /**
     * Remove ticket.
     *
     * @param \App\Entity\Ticket $ticket
     *
     * @return boolean TRUE if this collection contained the specified element, FALSE otherwise.
     */
    public function removeTicket(\App\Entity\Ticket $ticket)
    {
        return $this->ticket->removeElement($ticket);
    }

    /**
     * Get ticket.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTicket()
    {
        return $this->ticket;
    }

    /**
     * Add prize.
     *
     * @param \App\Entity\Prize $prize
     *
     * @return User
     */
    public function addPrize(\App\Entity\Prize $prize)
    {
        $this->prize[] = $prize;

        return $this;
    }

    /**
     * Remove prize.
     *
     * @param \App\Entity\Prize $prize
     *
     * @return boolean TRUE if this collection contained the specified element, FALSE otherwise.
     */
    public function removePrize(\App\Entity\Prize $prize)
    {
        return $this->prize->removeElement($prize);
    }

    /**
     * Get prize.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPrize()
    {
        return $this->prize;
    }

    /**
     * Returns the roles granted to the user.
     *
     * <code>
     * public function getRoles()
     * {
     *     return array('ROLE_USER');
     * }
     * </code>
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        $role = $this->groups->toArray(); 
        return array($role[0]->getRole());
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string The password
     */
    public function getPassword()
    {
        return $this->password;
    }
    public function setPassword($password)
    {
        $this->password = $password;
    }


    public function getPlainPassword()
    {
        return $this->plainPassword;
    }
    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }


    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        return null;
    }

    /**
     * Set tokenId.
     *
     * @param int|null $tokenId
     *
     * @return User
     */
    public function setTokenId($tokenId = null)
    {
        $this->token_id = $tokenId;

        return $this;
    }

    /**
     * Get tokenId.
     *
     * @return int|null
     */
    public function getTokenId()
    {
        return $this->token_id;
    }

    /**
     * Set facebookId.
     *
     * @param string|null $facebookId
     *
     * @return User
     */
    public function setFacebookId($facebookId = null)
    {
        $this->facebook_id = $facebookId;

        return $this;
    }

    /**
     * Get facebookId.
     *
     * @return string|null
     */
    public function getFacebookId()
    {
        return $this->facebook_id;
    }

    /**
     * Set googleId.
     *
     * @param string|null $googleId
     *
     * @return User
     */
    public function setGoogleId($googleId = null)
    {
        $this->google_id = $googleId;

        return $this;
    }

    /**
     * Get googleId.
     *
     * @return string|null
     */
    public function getGoogleId()
    {
        return $this->google_id;
    }

    /**
     * Set dateCreate.
     *
     * @param \DateTime $dateCreate
     *
     * @return User
     */
    public function setDateCreate($dateCreate)
    {
        $this->date_create = $dateCreate;

        return $this;
    }

    /**
     * Get dateCreate.
     *
     * @return \DateTime
     */
    public function getDateCreate()
    {
        return $this->date_create;
    }

    /**
     * Set dateDelete.
     *
     * @param \DateTime|null $dateDelete
     *
     * @return User
     */
    public function setDateDelete($dateDelete = null)
    {
        $this->date_delete = $dateDelete;

        return $this;
    }

    /**
     * Get dateDelete.
     *
     * @return \DateTime|null
     */
    public function getDateDelete()
    {
        return $this->date_delete;
    }

    public function getCheckCgu(): ?bool
    {
        return $this->check_cgu;
    }

    public function setCheckCgu(bool $check_cgu): self
    {
        $this->check_cgu = $check_cgu;

        return $this;
    }

Lab/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('first_name', TextType::class)
                ->add('family_name', TextType::class)
                ->add('email', EmailType::class)
                ->add('plainPassword', RepeatedType::class, array(
                    'type' => PasswordType::class,
                    'first_options'  => array('label' => 'Mot de passe'),
                    'second_options' => array('label' => 'Répéter le Mot de passe'),
                ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

Lab/src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class UserController extends AbstractController
{
    /**
    * @Route("/admin/user/{page<\d+>?1}", name="user_index", methods={"GET", "POST"})
    * @IsGranted("IS_AUTHENTICATED_FULLY", message="Vous n'ètes pas connécté")
    */
    public function index(UserRepository $userRepository, Request $request, $page, PaginatorInterface $paginator): Response
    {
        $limit = 10;

        $searchBar = $this->createFormBuilder()
            ->add('query', TextType::class,array(
                'label' => false,
                'attr' => [
                    'class' => 'input is-primary inputSearchTicket',
                    'placeholder' => 'george@gmail.com',
                ]
            ))
            ->add('search', SubmitType::class, [
                'label' => 'Rechercher',
                'attr' => [
                    'class' => 'button is-primary btnSearchAdmin',
                ]
            ])->getForm();

        $searchBar->handleRequest($request);

        $queryUser = $request->request->get('form')['query'];
        $resSearch = $userRepository->searchUser($queryUser);

        if ($resSearch) {
            $users = $paginator->paginate(
                $resSearch,
                $page,
                $limit
            );
        } else {
            $users = $paginator->paginate(
                $userRepository->findAllVisibleQuery(),
                $page,
                $limit
            );
        }

        return $this->render('user/index.html.twig',[
            'users' => $users,
            'searchBar' => $searchBar->createView()
        ]);
    }


    /**
     * @Route("/admin/user/{id}/delete", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user, $id): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $query = $em->createQuery('DELETE App:User id  WHERE id = :userid')->setParameter("userid", $user->getId());
            $result = $query->execute();    
        }
        
        return $this->redirectToRoute('user_index');
    }


    /**
     * @Route("/admin/user/show/{id}", name="user_show", methods={"GET"})
     * @IsGranted("IS_AUTHENTICATED_FULLY", statusCode=401, message="Vous n'êtes pas connecté")
     */
    public function show(UserRepository $userRepository, User $user, $id): Response
    {
        $userRole = $userRepository->getRoleUser($id);

        return $this->render('user/show.html.twig', [
            'user' => $user,
            'role' => $userRole[0]
        ]);
    }
    
}

Lab/templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet utilisateur ?');">
	<input type="hidden" name="_method" value="DELETE">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
	<center>
		<button class="button btnDelete" {% if is_granted("ROLE_USER") or is_granted("ROLE_EMP") %} disabled {% endif %}>
			<i class="fa fa-trash"></i>
		</a>
	</button>
</center></form>

Lab/templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panel Admin - Utilisateur
{% endblock %}

{% block body %}
	{% if users is not empty %}
		<div id="admin-utilisateurs" class="flex-1">
			<div class="columns h-100">
				{% include 'panel_admin/sidebar-admin.html.twig' with {'page': 'Utilisateurs'} %}
				<div class="column is-9-desktop is-8-tablet is-12-mobile bg-admin">
					<div class="columns">
						<div class="column is-10 is-offset-1">
							<h1 class="title is-1 p-b-lg p-t-lg has-text-centered">
								<u>Utilisateurs</u>
							</h1>
							{{ form_start(searchBar, {'attr': {'class': 'searchBar section p-b-none'}})  }}
							{{ form_label(searchBar, null, {'label': 'Rechercher l\'email de l\'utilisateur','label_attr': {'for': 'form_query'}}) }}
							{{ form_widget(searchBar) }}
							{{ form_end(searchBar) }}
							<div class="section">
								<div class="card">
									<div class="card-header">
										<p class="card-header-title">Utilisateurs</p>
									</div>
									<div class="card-content">
										<div class="content table-container">
											<table class="table is-fullwidth">
												<thead>
													<tr>
														<th>Profile</th>
														<th>Id</th>
														<th>Email</th>
														<th>Nom</th>
														<th>Prénom</th>
														<th>Date Creation</th>
														<th>Supprimer</th>
													</tr>
												</thead>
												<tbody>
													{% for user in users %}
														<tr>
															<center>
																<td>
																	<figure class="image is-32x32">
																		<a href="{{ path('user_show', {'id': user.id}) }}"><img class="is-rounded" src="{{ user.imageUrl }}"></a>
																	</figure>
																</td>
															</center>
															<td>{{ user.id }}</td>
															<td>{{ user.firstName }}</td>
															<td>{{ user.familyName }}</td>
															<td>{{ user.email }}</td>
															<td>{{ user.dateCreate | date("d/m/Y") }}</td>
															<td>
																{{ include('user/_delete_form.html.twig') }}
															</td>
														</tr>
													{% endfor %}
												</tbody>
											</table>
										</div>
									</div>
								</div>
								{{ knp_pagination_render(users) }}
							</div>
						</div>
					</div>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

Lab/templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panel Admin - Utilisateur
{% endblock %}

{% block body %}
	<div id="admin-utilisateurs" class="flex-1">
		<div class="columns h-100">
			{% include 'panel_admin/sidebar-admin.html.twig' with {'page': 'Utilisateurs'} %}
			<div class="column is-9-desktop is-8-tablet is-12-mobile bg-admin d-flex flex-column justify-content-center">
				<div class="columns">
					<div class="column is-10 is-offset-1">
						<h1 class="title is-1 p-b-lg p-t-lg has-text-centered m-b-none">
							<u>Utilisateurs</u>
						</h1>
						<div class="section">
							<h2 class="has-text-centered p-b-lg is-size-5 has-text-weight-bold">{{ user.firstName }}
								{{ user.familyName }}</h2>
							<div class="box">
								<article class="media">
									<div class="media-left">
										<figure class="image is-64x64">
											<img src="{{ user.imageUrl }}">
										</figure>
									</div>
									<div class="media-content">
										<div class="content">
											<p>
												<strong>ID :</strong>
												<span>{{ user.id }}</span>
											</p>
											<p>
												<strong>Nom :</strong>
												<span class="is-uppercase">{{ user.familyName }}</span>
											</p>
											<p>
												<strong>Prénom :</strong>
												<span>{{ user.firstName }}</span>
											</p>
											<p>
												<strong>Adresse mail :</strong>
												<span>{{ user.email }}</span>
											</p>
											<p>
												<strong>Rôle de l'utilisateur :</strong>
												<span>
													{% if role.name is not null %}
														{{ role.name }}
													{% else %}
														Aucun rôle
													{% endif %}
												</span>
											</p>
											<p>
												<strong>Abonné à la newsletter :</strong>
												<span>
													{% if user.checkNewsletter == false %}
														Non abonné
													{% else %}
														Abonné
													{% endif %}
												</span>
											</p>
											<small>
												<b>
													<i>Créer le
														<td>{{ user.dateCreate | date("d/m/Y") }}</td>
													</i>
												</b>
											</small>
											<div style="float: right;">{{ include('user/_delete_form.html.twig') }}</div>
										</p>
									</div>
								</article>
							</div>
							<a href="{{ path('user_index') }}" class="has-text-dark">
								<i class="fas fa-arrow-left"></i>
								retour à la liste</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}